export const SET_BPM = 'SET_BPM';

export const LOAD_SAMPLE = 'LOAD_SAMPLE';
export const LOAD_SAMPLE_SUCCESS = 'LOAD_SAMPLE_SUCCESS';
export const SAMPLES_ARE_LOADED = 'SAMPLES_ARE_LOADED';

export const SELECT_SAMPLE_PATTERN = 'SELECT_SAMPLE_PATTERN';
export const RESET_PATTERN = 'RESET_PATTERN';
export const FLIP_PATTERN_SWITCH = 'FLIP_PATTERN_SWITCH';

export const PLAY_SOUNDS = 'PLAY_SOUNDS';

export const BPM_TICK = 'BPM_TICK';
export const BPM_TOCK = 'BPM_TOCK';

export const BPM_PART_TICK = 'BPM_PART_TICK';
export const BPM_PART_TOCK = 'BPM_PART_TOCK';
